# Run the nightly E2E tests on desktop browsers on prod using BrowserStack; prod uses Backblaze for backend storage
name: nightly-tests-mobile

concurrency:
  group: nightly-tests-mobile
  cancel-in-progress: true

on:
  schedule:
    # run every day at 2:30am UTC (9:30 PM EST)
    - cron:  '30 2 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  packages: read
  contents: read    # This is required for actions/checkout

jobs:
  nightly-prod-mobile-e2e:
    name: nightly-prod-mobile-e2e
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/cached-devcontainer:latest
    environment: production
    env:
      TBPRO_USERNAME: ${{ secrets.E2E_NIGHTLY_PROD_TBPRO_USERNAME }}
      TBPRO_PASSWORD: ${{ secrets.E2E_NIGHTLY_PROD_TBPRO_PASSWORD }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd ./packages/send/e2e
          npm install

      - name: BrowserStack Env Setup
        uses: browserstack/github-actions/setup-env@master
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          project-name: 'Thunderbird Send'
          build-name: 'TB Send Nightly E2E Tests (Desktop): BUILD_INFO'

      - name: Prod E2E Tests on Android Chrome
        # don't send GHA failure email if any of the E2E tests fail, can be annoying (check the jobs each day in BrowserStack)
        continue-on-error: true
        run: |
          cd ./packages/send/e2e
          cp .env.prod.sample .env
          npm run test:e2e:nightly:prod:browserstack:mobile:android:chrome

      - name: Prod E2E Tests on iOS Safari
        # don't send GHA failure email if any of the E2E tests fail, can be annoying (check the jobs each day in BrowserStack)
        continue-on-error: true
        run: |
          cd ./packages/send/e2e
          cp .env.prod.sample .env
          npm run test:e2e:nightly:prod:browserstack:mobile:ios:safari
