# Run the nightly E2E tests on desktop browsers on prod using BrowserStack; prod uses Backblaze for backend storage
name: nightly-tests-desktop

concurrency:
  group: nightly-tests-desktop
  cancel-in-progress: true

on:
  schedule:
    # run every day at 2am UTC (9PM EST)
    - cron:  '0 2 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read    # This is required for actions/checkout

jobs:
  nightly-prod-desktop-e2e:
    name: nightly-prod-desktop-e2e
    runs-on: ubuntu-latest
    environment: production
    env:
      TBPRO_USERNAME: ${{ secrets.TBPRO_USERNAME }}
      TBPRO_PASSWORD: ${{ secrets.TBPRO_PASSWORD }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'test/e2e/package-lock.json'

      - name: Install dependencies
        run: |
          cd ./packages/send
          npm install

      - name: BrowserStack Env Setup
        uses: browserstack/github-actions/setup-env@master
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          project-name: 'Thunderbird Send'
          build-name: 'TB Send Nightly E2E Tests (Desktop): BUILD_INFO'

      - name: Prod E2E Tests on Desktop Firefox
        # don't send GHA failure email if any of the E2E tests fail, can be annoying (check the jobs each day in BrowserStack)
        continue-on-error: true
        run: |
          cd ./packages/send/e2e
          cp .env.prod.sample .env
          npm run test:e2e:nightly:prod:browserstack:desktop:firefox

      - name: Prod E2E Tests on Desktop Safari Webkit
        # don't send GHA failure email if any of the E2E tests fail, can be annoying (check the jobs each day in BrowserStack)
        continue-on-error: true
        run: |
          cd ./packages/send/e2e
          cp .env.prod.sample .env
          npm run test:e2e:nightly:prod:browserstack:desktop:safari

      - name: Prod E2E Tests on Desktop Chromium
        # don't send GHA failure email if any of the E2E tests fail, can be annoying (check the jobs each day in BrowserStack)
        continue-on-error: true
        run: |
          cd ./packages/send/e2e
          cp .env.prod.sample .env
          npm run test:e2e:nightly:prod:browserstack:desktop:chromium
