name: 'setup' 
on: # rebuild any PRs and main branch changes
  pull_request:
  push:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - dev-container-tests
      - name: Setup send env
        uses: devcontainers/ci@v0.3
        with:
          # Change this to point to your image name
          cacheFrom: ghcr.io/aatchison/tbpro-addon/cached-devcontainer
          push: never
          # Change this to be your CI task/script
          runCmd: echo "Y" | lerna run setup --scope=send-suite

      - name: Setup addon env
        uses: devcontainers/ci@v0.3
        with:
          # Change this to point to your image name
          cacheFrom: ghcr.io/aatchison/tbpro-addon/cached-devcontainer
          push: never
          # Change this to be your CI task/script
          runCmd: echo "Y" | lerna run setup --scope=addon