name: 'setup' 
on: # rebuild any PRs and main branch changes
  pull_request:
  push:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Setup send env
      #   uses: devcontainers/ci@v0.3
      #   with:
      #     # Change this to point to your image name
      #     cacheFrom: ghcr.io/aatchison/tbpro-addon/cached-devcontainer
      #     push: never
      #     # Change this to be your CI task/script
      #     runCmd: echo "Y" | lerna run setup --scope=send-suite

      - name: Setup addon env
        uses: devcontainers/ci@v0.3
        with:
          # Change this to point to your image name
          cacheFrom: ghcr.io/aatchison/tbpro-addon/cached-devcontainer
          push: never
          # Change this to be your CI task/script
          runCmd: echo "Y" | lerna run setup --scope=addon

      - name: Build addon
        uses: devcontainers/ci@v0.3
        with:
          # Change this to point to your image name
          cacheFrom: ghcr.io/aatchison/tbpro-addon/cached-devcontainer
          push: never
          # Change this to be your CI task/script
          runCmd: pnpm install && echo "Y" | lerna run build --scope=addon