name: 'test' 
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - dev-container-tests

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and cache devcontainer
        uses: devcontainers/ci@v0.3
        with:
          # Change this to point to your image name
          imageName: ghcr.io/aatchison/tbpro-addon/cached-devcontainer
          cacheFrom: ghcr.io/aatchison/tbpro-addon/cached-devcontainer
          push: always
          # Change this to be your CI task/script
          runCmd: pnpm install --filter @thunderbird/tbpro-add-on && lerna run bootstrap

      - name: Setup send env
        uses: devcontainers/ci@v0.3
        with:
          # Change this to point to your image name
          cacheFrom: ghcr.io/aatchison/tbpro-addon/cached-devcontainer
          push: always
          # Change this to be your CI task/script
          runCmd: lerna run setup --scope=send-suite

      - name: Setup addon env
        uses: devcontainers/ci@v0.3
        with:
          # Change this to point to your image name
          cacheFrom: ghcr.io/aatchison/tbpro-addon/cached-devcontainer
          push: always
          # Change this to be your CI task/script
          runCmd: lerna run setup --scope=addon